### ISSUE TITLE
Checklist for v1.0.0

### ISSUE THREAD

**Issue by dmattia** [dmattia/vue-firebase#2]
- [ ] separate FireQuery and FireDocument components
- [ ] add unit tests
- [ ] add Cypress e2e tests for demo page
- [ ] FireMutation component or use two way data binding
- [ ] support all Firebase Query props in FireQuery
- [ ] authentication component
- [ ] login component
- [ ] caching queries in local storage
- [ ] documentation/demo website
- [ ] infinite grid and/or pagination components
- [ ] Firestore support
- [ ] editable table component
- [ ] components for enforcing login roles
- [ ] storage upload component
- [ ] storage query component
